import type { NextApiResponse } from "next";

export const ADMIN_ERROR_CODES = {
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  METHOD_NOT_ALLOWED: "METHOD_NOT_ALLOWED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  AFFILIATE_NOT_FOUND: "AFFILIATE_NOT_FOUND",
  MISSING_AFFILIATE_ID: "MISSING_AFFILIATE_ID",
  INVALID_AFFILIATE_ID: "INVALID_AFFILIATE_ID",
  MISSING_IDENTIFIER: "MISSING_IDENTIFIER",
  LISTING_OR_PAYMENT_NOT_FOUND: "LISTING_OR_PAYMENT_NOT_FOUND",
  NOT_DIRECTORY_PURCHASE: "NOT_DIRECTORY_PURCHASE",
  UNPAID_LISTING: "UNPAID_LISTING",
  MISSING_STRIPE_SESSION_ID: "MISSING_STRIPE_SESSION_ID",
  DIRECTORY_LISTING_NOT_FOUND: "DIRECTORY_LISTING_NOT_FOUND",
  LISTING_NOT_PAID: "LISTING_NOT_PAID",
  LISTING_UNLINKED: "LISTING_UNLINKED",
} as const;

export function adminFail(
  res: NextApiResponse,
  status: number,
  code: string,
  message: string,
) {
  return res.status(status).json({ ok: false, code, message });
}
